### ISSUE TITLE
Stylelint complains that the class is not in kebab-case

### ISSUE THREAD

**Issue by Anthony-Gaudino** [pascalduez/stylelint-config-css-modules#13]
After installing and setting up the `extends` in `Package.json`:

```json
  "stylelint": {
    "extends": [
      "stylelint-config-recess-order",
      "stylelint-config-standard-scss",
      "stylelint-config-css-modules"
    ]
  },
```

Stylelint complains that class names are not in `kebab-case` even though CSS modules should be in camelCase.

I think this may not be working at all, since in VSCode it says that the `@value` is an `Unknown at rule`.

**Comment by pascalduez** [comment]
Hi,

for the case issue, please see https://github.com/pascalduez/stylelint-config-css-modules/issues/7.   
It's not in the scope of this preset to enforce this, it's a per project style decision, it's not only targeted at modules.  

> CSS modules should be in camelCase

CSS modules does not enforce camelCase.

> I think this may not be working at all, since in VSCode it says that the @value is an Unknown at rule.

It's working well (see tests). Probably check your VSCode config to make sure it uses the proper config.

**Comment by SalahAdDin** [comment]
But we installed it to fix that issue @pascalduez.
