### ISSUE TITLE
Stylelint complains that Classnames are not in kebab-case

### ISSUE THREAD

**Issue by Tanja-MM** [pascalduez/stylelint-config-css-modules#14]
I've installed the stylelint-config-css-modules additionally to the stylelint-config-standard-scss package. 

package.json: 

` "stylelint": "^14.16.0",
    "stylelint-config-standard-scss": "^6.1.0",
    "stylelint-css-modules": "^1.2.2",`

my stylelintrc file looks like this: 

`{
  "plugins": [
    "stylelint-scss"
  ],
  "extends": [
    "stylelint-config-standard-scss",
    "stylelint-config-css-modules"
  ]
}`

and I still get the following error when running _npm stylelint "**/*.scss"_: 

 ```
7:1   ✖  Expected class selector ".objektFormWrapper" to be kebab-case                                           selector-class-pattern
  8:3   ✖  Expected class selector ".formFieldsWrapper" to be kebab-case                                           selector-class-pattern
  9:5   ✖  Expected class selector ".emptyDatePicker" to be kebab-case                                             selector-class-pattern
 15:1   ✖  Expected class selector ".progressBarWrapper" to be kebab-case                                          selector-class-pattern
```

Did I forgot to configure or import anything or does the package not work?

**Comment by pascalduez** [comment]
Hello,

please see for the reasoning https://github.com/pascalduez/stylelint-config-css-modules/issues/13#issuecomment-1266763160
