### ISSUE TITLE
this config is not compatibility with stylelint-config-recommended-scss

### ISSUE THREAD

**Issue by nztraveler** [pascalduez/stylelint-config-css-modules#6]
I have use sass and css modules in my project. 
So, I use stylelint like this:
`module.exports = {
  extends: [
'stylelint-config-recommended-scss', 
'stylelint-config-css-modules'
],
};`

it will lead to the error of unexpected unknown at-rule like below
![image](https://user-images.githubusercontent.com/22699159/72320639-11a63900-36dd-11ea-836a-acf989220c59.png)

**Comment by pascalduez** [comment]
Hi @nztraveler,

this has nothing to do with `stylelint-config-css-modules`, but you need to make stylelint accept the Sass or Scss syntax. 

The way I do it is though the cli, but there's probably other ways.

```
stylelint --syntax scss 'src/**/*.scss'
```

**Comment by pascalduez** [comment]
Ah humm sorry, I've read the issue way to fast :)   
Well, that's a problem, as far as I know, there's not way for rules to "deep extend" or "merge options" between them.   
So here what happens it the `at-rule-no-unknow` rule from `stylelint-config-css-modules` completely overriding the one from `stylelint-config-recommended-scss`.

**Comment by kroko** [comment]
@nztraveler In case of SCSS _at-rule-no-unknown_ should be set to null and _scss/at-rule-no-unknown_ should be used. You should just compose your own stylelint config.

_.stylelintrc.js_

```javascript
// keep json compatible key naming and comma trailing

/* eslint-disable quotes, quote-props */

module.exports = {
  "extends": [
    "stylelint-config-standard"
  ],
  "plugins": [
    "stylelint-scss"
  ],
  "rules": {

    "no-empty-source": null, // https://stylelint.io/user-guide/rules/no-empty-source

    "rule-empty-line-before": "always", // https://stylelint.io/user-guide/rules/rule-empty-line-before

    "block-closing-brace-empty-line-before": null, // https://stylelint.io/user-guide/rules/block-closing-brace-empty-line-before
    "max-empty-lines": [ // https://stylelint.io/user-guide/rules/max-empty-lines
      2,
      {
        "ignore": [
          "comments"
        ]
      }
    ],

    "at-rule-no-unknown": null, // disable and use scss/at-rule-no-unknown

    // --------------------------------------------
    // RULES FOR SCSS TO WORK

    "block-opening-brace-space-before": "always", // https://stylelint.io/user-guide/rules/block-opening-brace-space-before
    "block-closing-brace-newline-after": [ // https://stylelint.io/user-guide/rules/block-closing-brace-newline-after
      "always",
      {
        "ignoreAtRules": [
          "if",
          "else"
        ]
      }
    ],

    "at-rule-empty-line-before": [ // https://stylelint.io/user-guide/rules/at-rule-empty-line-before
      "always",
      {
        "ignoreAtRules": [
          "else",
          "import"
        ]
      }
    ],
    "at-rule-name-space-after": "always", // https://stylelint.io/user-guide/rules/at-rule-name-space-after

    // "scss/at-rule-no-unknown": true, // https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-rule-no-unknown/README.md
    "scss/at-else-closing-brace-newline-after": "always-last-in-chain", // https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-else-closing-brace-newline-after/README.md
    "scss/at-else-closing-brace-space-after": "always-intermediate", // https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-else-closing-brace-space-after/README.md
    "scss/at-if-closing-brace-newline-after": "always-last-in-chain", // https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-if-closing-brace-newline-after/README.md
    "scss/at-if-closing-brace-space-after": "always-intermediate", // https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-if-closing-brace-space-after/README.md

    // --------------------------------------------
    // STYLELINT RULES FOR CSS MODULES

    "selector-pseudo-class-no-unknown": [
      true,
      {
        ignorePseudoClasses: [
          "export",
          "import",
          "global",
          "local",
          "external"
        ]
      }
    ],
    "selector-type-no-unknown": [
      true,
      {
        "ignoreTypes": ["from"]
      }
    ],
    "property-no-unknown": [
      true,
      {
        "ignoreProperties": ["composes", "compose-with"],
        "ignoreSelectors": [":export", /^:import/]
      }
    ],
    // "at-rule-no-unknown": [
    "scss/at-rule-no-unknown": [
      true,
      {
        "ignoreAtRules": ["value"]
      }
    ]

  }
};
```

**Comment by lvnam96** [comment]
Is there any update on this issue?

Maybe another repo/config called `stylelint-config-scss-modules` using `scss/at-rule-no-unknown` instead of `at-rule-no-unknown` & let people know in README?

Or can we create another export from this repo (I'm not sure how packages work)? I mean:
```js
// .stylelintrc
{
  "extends": [
    "stylelint-config-recommended-scss",
    "stylelint-config-css-modules/scss"
  ],
}
```

**Comment by nam-diijam** [comment]
Here is a workaround:
```
// .stylelintrc
{
  "extends": [
    "stylelint-config-recommended-scss",
    "stylelint-config-css-modules"
  ],
  "rules": {
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": [
      true,
      {
        "ignoreAtRules": [
          "value"
        ]
      }
    ]
  }
}
```

Basically I just moved this rule setting `"ignoreAtRules": [ "value" ]` from `at-rule-no-unknown` to `scss/at-rule-no-unknown`

**Comment by fgblomqvist** [comment]
@pascalduez Would you accept a PR for the above solution? E.g. adding `stylelint-config-css-modules/scss` to this repo. It would probably just be the solution that @lvnam96 proposed, to keep things DRY.

**Comment by fgblomqvist** [comment]
Any comment on this @pascalduez? This config still causes issues with SCSS ones. It would be really easy with Stylelint 14 to utilize overrides to only enable the above mentioned rules (and `function-no-unknown`) for CSS files.

**Comment by pascalduez** [comment]
I gave it a go in #10. Please have a look.

Altough @fgblomqvist I couldn't find any `function-no-unknown` rule in `styleint-scss` yet, so overriding the rule had no effect. 
It looks like we'll have to wait for https://github.com/stylelint-scss/stylelint-scss/pull/591 to benefit from their rule.

**Comment by fgblomqvist** [comment]
@pascalduez There is still a point to overriding the rule, simply disabling it. Otherwise it will keep warning on common SCSS functions.
