### ISSUE TITLE
Strange symbols in error message

### ISSUE THREAD

**Issue by wrqqq** [pascalduez/stylelint-config-css-modules#9]
![image](https://user-images.githubusercontent.com/20317511/131720677-2115469d-9ce3-4a28-9db3-782609297512.png)
stylelint config:
```
{
    "extends": ["stylelint-config-standard", "stylelint-config-css-modules"]
}
```
windows 10, any code formatting errors?

**Comment by pascalduez** [comment]
It's just a shared config file here, we don't deal with output etc. So probably the wrong place.
